apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "wishlist-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport}}
      protocol: TCP
      name: http
  selector:
    {{- include "wishlist-helm.selectorLabels" . | nindent 4 }}
