apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "cart-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicacount }}
  selector:
    matchLabels:
      {{- include "cart-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cart-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.deployment.image.repository | quote }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
